import enum

class StatusEnum(str, enum.Enum):
    NEW = "NEW"
    ON_VERIFICATION = "ON_VERIFICATION"
    ON_REVIEW = "ON_REVIEW"
    ACCEPTED = "ACCEPTED"
    CONFLICT = "CONFLICT"

class RiskStatusEnum(str, enum.Enum):
    COMPLY = "COMPLY"
    RISK = "RISK"

class JenisKontrakEnum(str, enum.Enum):
    LAYANAN_TEKNOLOGI_INFORMASI = "LAYANAN_TEKNOLOGI_INFORMASI"
    PENGADAAN_BARANG_JASA = "PENGADAAN_BARANG_JASA"
    KEMITRAAN_GLOBAL = "KEMITRAAN_GLOBAL"
    INTEGRASI_LOGISTIK = "INTEGRASI_LOGISTIK"
    JASA_KEPELABUHAN_DIGITAL = "JASA_KEPELABUHAN_DIGITAL"